### PR TITLE
Update code for 93

### PR DESCRIPTION
**Pull request by tsmr**
Update code for 93

### CODE REVIEW

**Comment by cedric-anne** [comment]
Hi,

9.3 compatiblity has been done in https://github.com/pluginsGLPI/openvas/pull/22.

You shoul make a PR only with the new Dashboard feature.

Regards

**Comment by cedric-anne** [comment]
Hi,

I switched target branch to develop, as this PR is not a hotfix.
Please cleanup your PR to keep only the new feature. Compatibility code for 9.3 has been already done and will be released soon.

Regards

**Comment by Gydvins** [comment]
Good afternoon, are there any plans for OpenVas to be compatible with GLPI 10.0.15? Thanks in advance for your answer!

**Comment by trasher** [comment]
This plugin has not been updated in the last 6 years, it certainly won't be on a community basis :)

I'll close thi sold dead PR also.

**Pull request closed without merging**
